# Generated by Django 5.2.6 on 2025-09-25 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("balance", "Rozvaha / Balance sheet"),
                            ("income", "Výsledovka / Income statement"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField(default=1)),
                ("table_index", models.PositiveIntegerField(default=1)),
                ("method", models.CharField(default="merged", max_length=50)),
                ("columns", models.JSONField(default=list)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="ingestion.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("value", models.FloatField(blank=True, db_index=True, null=True)),
                (
                    "section",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="ingestion.extractedtable",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="extractedtable",
            index=models.Index(
                fields=["document", "page_number"],
                name="ingestion_e_documen_2918cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="extractedrow",
            index=models.Index(fields=["code"], name="ingestion_e_code_69dce7_idx"),
        ),
        migrations.AddIndex(
            model_name="extractedrow",
            index=models.Index(
                fields=["section"], name="ingestion_e_section_6ac27f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedrow",
            index=models.Index(fields=["value"], name="ingestion_e_value_a588fd_idx"),
        ),
    ]
