# Generated by Django 5.2.6 on 2025-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedrow",
            name="label",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="extractedrow",
            index=models.Index(fields=["label"], name="ingestion_e_label_aa17e6_idx"),
        ),
    ]
