# Generated by Django 5.2.6 on 2025-09-24 14:15

import django.db.models.deletion
import ingestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                blank=True,
                choices=[("balance", "Rozvaha"), ("income", "Výsledovka")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="statement_date",
            field=models.DateField(blank=True, help_text="Datum výkazu", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=ingestion.models.upload_to_document),
        ),
    ]
