# Generated by Django 5.2.6 on 2025-09-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_document_doc_type_document_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="statement_date",
        ),
    ]
