# Generated by Django 5.2.6 on 2025-09-25 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("VÍCE ČASU", "VÍCE ČASU"),
                            ("VÍCE PENĚZ", "VÍCE PENĚZ"),
                            ("MÉNĚ STRACHU", "MÉNĚ STRACHU"),
                        ],
                        max_length=32,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("ai_response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="suropen_ope_user_id_6f0ab9_idx",
                    ),
                    models.Index(
                        fields=["batch_id"], name="suropen_ope_batch_i_61ae88_idx"
                    ),
                ],
            },
        ),
    ]
