# Generated by Django 5.2.6 on 2025-09-25 21:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Název firmy"),
                ),
                (
                    "respondent_name",
                    models.CharField(max_length=255, verbose_name="Jméno účastníka"),
                ),
                (
                    "respondent_email",
                    models.EmailField(max_length=254, verbose_name="Email respondenta"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Telefonní číslo",
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Informace o sobě / poznámka",
                    ),
                ),
                (
                    "ico",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="IČO"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Odvětví"
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        choices=[
                            ("micro", "Mikro (1–10 zaměstnanců)"),
                            ("small", "Malá (11–50 zaměstnanců)"),
                            ("medium", "Střední (51–250 zaměstnanců)"),
                            ("large", "Velká (250+ zaměstnanců)"),
                        ],
                        max_length=20,
                        verbose_name="Velikost firmy",
                    ),
                ),
                (
                    "coach",
                    models.CharField(
                        choices=[
                            ("coach1", "Kouč 1"),
                            ("coach2", "Kouč 2"),
                            ("coach3", "Kouč 3"),
                        ],
                        max_length=50,
                        verbose_name="Kouč",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Datum zpracování",
                    ),
                ),
            ],
        ),
    ]
